### PR TITLE
Fix `spectatorPlayersUsePortals` crashing client side when running on multiplayer server

### LINKED ISSUE #157: [BUG] - Client disconnect when entering a nether portal as a spectator in a multiplayer server.
### Description
 
When entering a nether portal in spectator with the rule spectatorPlayersUsePortals set to true, the client is disconnected with the error "Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet"

### To Reproduce

1. Open multiplayer world
2. Do `/carpet spectatorPlayersUsePortals true`
3. Go into spectator mode
4. Enter portal
5. See error

### Expected behavior
The expected behavior was that the player would enter the nether portal and be transported to the nether.

### Screenshots
[latest.log](https://github.com/Gilly7CE/Carpet-Addons-Not-Found/files/11725315/latest.log)

### Version (please complete the following information):
 - Minecraft version: 1.19.4
 - Carpet version: 1.4.101+v230319
 - Mod version: 1.2.1

### PR DESCRIPTION
**Pull request by Gilly7CE**
The crash was due to the custom packet we added not being a registered packet on the client side when the mod is used in a multiplayer enviroment.

Fix is to bring in the mechanism base Carpet mod does to sync client and server side. This works for single-player, and the custom payload handler will only work for the client side in multiplayer if the client also has the mod installed. This is fine in my opinion, will just need to add a note to the release notes.

Fixes #157

### CODE REVIEW

File: src/main/java/carpetaddonsnotfound/network/ClientNetworkHandler.java [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+   */
+  private static void onSyncData(PacketByteBuf data, ClientPlayerEntity player) {
+    NbtCompound compound = data.readNbt();
+    if (compound == null) {
+      return;
+    }
+
+    for (String key : compound.getKeys()) {
+      if (!dataHandlers.containsKey(key)) {
+        CarpetSettings.LOG.error("Unknown carpet data: " + key);
```
Comment (Gilly7CE) [inline src/main/java/carpetaddonsnotfound/network/ClientNetworkHandler.java:97]: Should be our Settings class
